spring:
  application:
    name: bda

  config:
    import:
      - "optional:file:.env[.properties]"
      - "optional:configtree:/run/secrets/"

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${db_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    sql-migration-prefix: v
    baseline-on-migrate: true
    baseline-version: 0

server:
  port: 8080
  servlet:
    context-path: /api

version:
  path: v1

jwt:
  secret: ${jwt_secret}
  expiration-ms: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs.yaml
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.bda.bda.controller.v1
  paths-to-match: /v1/**