spring:
  application:
    name: bda

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bda}
    username: ${DB_USER:masterpiece}
    password: ${DB_PASS:comebaaaaaaaaaaaaaaack}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  servlet:
    context-path: /api

version:
  path: v1

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /api/v3/api-docs.yaml
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.bda.bda.controller.v1
  paths-to-match: /v1/**
